#!/bin/bash
##PBS -N test_gp
##PBS -N dynesty_wp_upf_mcf_all
##PBS -N dynesty_wp_hodnofv_mcut115_seed23_dlogz001
##PBS -N dynesty_wp_hod-no-alpha-msat_dlogz001
#PBS -N dynesty_wp_xi_upf_mcf_all_dlogz0000001_seed12
##PBS -N dynesty_wp_mcf_all_dlogz01
##PBS -N dynesty_wp_xi_upf_mcf_all_hprior
##PBS -N dynesty_wp_omegam-sigma8-f_hprior
##PBS -N wp_upf_c3h3_omegam_sigma8_covperf
##PBS -N upf_c3h3_omegam_omegab_sigma8_covfrac
##PBS -N upf_c3h3_allcosmo_covperf2
##PBS -N wp_upf_c3h3_allhod_covperf2
##PBS -N upf_c3h3_all_covperf
##PBS -N wp_upf_c3h3_5cosmo_covperf
##PBS -N upf_c3h3_msat_alpha_mcut_fenv_covfrac
##PBS -N upf_c3h3_allcosmo_covperf_nw250
##PBS -N wp_upf_allhod
#PBS -l walltime=500:00:00
#PBS -l nodes=1:ppn=24
#PBS -m ae
#PBS -o output/$PBS_JOBNAME.out
#PBS -j oe

cd $PBS_O_WORKDIR
PATH=$PBS_O_PATH
echo $PBS_O_WORKDIR
echo 'starting'
echo -n 'Job is running on node '; cat $PBS_NODEFILE
python run_chain.py
#conda activate george2
#python test_gp.py
echo 'done'

