#!/bin/bash
##PBS -N test_glam_wp
##PBS -N chains_wp_c3h3_omegam-sigma8-f_emcee_glamcov
##PBS -N chains_wp_xi_c1h1_all_dy_covsmoothgauss
#PBS -N chains_wp_xi_upf_mcf_c1h10_all_dy_covsmoothgauss1
##PBS -N chains_wp_xi_upf_mcf_c1h1_all_dy
##PBS -N chains_wp_xi_c1h1_all_dy
#PBS -l walltime=1000:00:00
#PBS -l nodes=1:ppn=24
#PBS -m ae
#PBS -o output/$PBS_JOBNAME.out
#PBS -j oe

cd $PBS_O_WORKDIR
PATH=$PBS_O_PATH
echo $PBS_O_WORKDIR
echo 'starting'
echo -n 'Job is running on node '; cat $PBS_NODEFILE
python run_chain.py ../chain_configs/chains_wp_xi_upf_mcf_c1h10.cfg
#python test_glam.py
echo 'done'

