#!/bin/sh
#PBS -N chain_wp_xi_upf_mcf_covsmoothgauss1
#PBS -l nodes=1:ppn=24

#PBS -t 0-20%4

#PBS -o output/$PBS_JOBNAME.out
#PBS -j oe
  
#cd $PBS_O_WORKDIR
echo $PBS_O_WORKDIR
cd /home/users/ksf293/emulator/code
echo $PBS_O_WORKDIR

echo "Hello from $PBS_ARRAYID..."
declare -i cosmo #need to declare variables to do arithmetic
declare -i hoddigit
declare -i hod
declare -i ncosmos

ncosmos=7
hoddigit=${PBS_ARRAYID}/ncosmos
cosmo=${PBS_ARRAYID}%ncosmos
hod=cosmo*10+hoddigit

echo "Running chain from config file chains_wp_xi_upf_mcf_c${cosmo}h${hod}_covsg1.cfg"

python run_chain.py ../chain_configs/chains_wp_xi_upf_mcf_c${cosmo}h${hod}_covsg1.cfg
